### ISSUE TITLE
Implementing List Screen - CheckList & WishList & packing items

### ISSUE THREAD

**Issue by flowersayo** [EFUB-ZEJE/ZEJE-FrontEnd#33]
# 01 체크리스트
![image](https://user-images.githubusercontent.com/86418674/185225708-0f04a1bb-6159-4027-bf3f-b9dd209b11ba.png)

# 02 위시리스트

![image](https://user-images.githubusercontent.com/86418674/185225929-8ff2c776-885f-4e33-9d1a-9672bf7c7a27.png)

# 03 짐싸기 아이템

![image](https://user-images.githubusercontent.com/86418674/185225949-139d57fa-316d-4086-98ef-769fe9f838c5.png)

---

# 01  ✅체크리스트  (구현완료)  

- [x] 리스트추가
- [x] 리스트토글
- [x] 리스트 편집모드
    - [x] 리스트삭제
    - [x] 리스트 전체삭제

- [x] 로컬스토리지에 저장
- [x] 로딩스피너 -> `react-native-loading-spinner-overlay` https://www.npmjs.com/package/react-native-loading-spinner-overlay 사용

- [x] 리스트 30개 초과시 제한걸기 

|사진|사진|
|------|---|
|<img width="431" alt="스크린샷 2022-08-09 오후 6 31 26" src="https://user-images.githubusercontent.com/86418674/185250803-e756f5f6-d26a-4dee-90a2-ffa92bd9e957.jpg">|<img width="429" alt="스크린샷 2022-08-09 오후 6 30 32" src="https://user-images.githubusercontent.com/86418674/185250810-908b6c8e-3bf8-44a5-b600-0f98d99a9331.jpg">|

# 02 🙏위시리스트

- [x] 최신순 / 과거순 정렬
- [x] 좋아요해제시 위시리스트에서 삭제
- [x] 아이템 추가 성공모달
- [ ] 위시리스트 조회 API
- [ ] 위시리스트 삭제 API
- [ ] 위시리스트 추가 API

# 03 📦 추천 제로웨이스트 짐싸기 아이템  (구현완료)  

- [x] 페이지 생성
- [x] 리스트 맵핑
- [x] 아이템 추가

**Comment by flowersayo** [comment]
![Screenshot_20220818-065829_Zeje.jpg](https://user-images.githubusercontent.com/86418674/185250803-e756f5f6-d26a-4dee-90a2-ffa92bd9e957.jpg)![Screenshot_20220818-065841_Zeje.jpg](https://user-images.githubusercontent.com/86418674/185250810-908b6c8e-3bf8-44a5-b600-0f98d99a9331.jpg)

**Comment by flowersayo** [comment]
# 질문 To Backend  @siyeonkm @lcheun 

1. 여행지 조회 API 에서 사진 URL 정보가 빠진 것 같습니다.
2. 위시리스트를 최신순 or 과거순으로 정렬해야 하는데 명세서에는 시간과 관련된 속성이 없는 것 같습니다. 시간 순서대로 주시는거라고 이해하고 있으면 될까요? 
아니라면, 프론트측에서 사용자가 여행지를 위시리스트에 추가할때  `Date.now()` 활용해서 `"1660834565279"` 처럼 현재 경과된 시간을 반환하는 숫자값을 드릴 수 있을 것 같습니다! (숫자가 클수록 최신) 



![image](https://user-images.githubusercontent.com/86418674/185428418-063ea1e8-451d-43fe-8762-ea0e8ad137a1.png)

**Comment by lcheun** [comment]
1. 해당 정보 반영하여 api 문서 수정해두겠습니다.
2. 위시리스트가 저장되는 순서대로 아이디를 붙여서 자연스럽게 과거순 정렬이 될 것 같은데, 확실하게 두려면 시간순 설정 반영해서 수정할 수 있을 것 같습니다!

**Comment by flowersayo** [comment]
> 1. 해당 정보 반영하여 api 문서 수정해두겠습니다.
> 
> 2. 위시리스트가 저장되는 순서대로 아이디를 붙여서 자연스럽게 과거순 정렬이 될 것 같은데, 확실하게 두려면 시간순 설정 반영해서 수정할 수 있을 것 같습니다!

👍넵 알겠습니다 감사합니다~
